---
title: "About"
author: "Farah M"
date: "12/27/2020"
output: html_document
---

### About Next Word Predictor

Next Word Predictor is a Shiny app that uses a text prediction algorithm to predict the next word(s) based on text that is entered by the user.

#### How it works

The maximum likelihood estimation or MLE was used to estimate the probabilities that is assigned to the N-gram models. Then the Stupid Back-off algorithm is applied to get the next word prediction. Finally, the Kneser-Ney smoothing is used when there is insufficient match results.

For this application, the n-grams used are: quadgrams, trigrams, bigrams and unigrams. 
The n-grams models created from samples of twitter, blog and news text taken from a corpus called HC Corpora. 


#### Additional documentation

Presentation slides fo this application may be found in: https://rpubs.com/sarizzuz/NWPpresentation

Application code for this is available in github: 

1. Shiny Application code: https://github.com/sarizzuz/dscapstone/tree/main/NextWordPredictor

2. N-gram Modeling code: https://github.com/sarizzuz/dscapstone

The corpus text can be downloaded here:  https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip





#### This application was developed using:

+ [The R Project for Statistical Computing](https://www.r-project.org/)

+ [RStudio](https://www.rstudio.com/)

+ [Shiny](https://shiny.rstudio.com/reference/shiny/)
